<a href="https://colab.research.google.com/github/etamilselvan/Practice-/blob/master/Horse_Survival.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import the required Libraries
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('/content/horse.csv')

In [ ]:
df.head()

surgery    age  hospital_number  ...  lesion_2  lesion_3  cp_data
0      no  adult           530101  ...         0         0       no
1     yes  adult           534817  ...         0         0       no
2      no  adult           530334  ...         0         0      yes
3     yes  young          5290409  ...         0         0      yes
4      no  adult           530255  ...         0         0       no

[5 rows x 28 columns]

In [ ]:
df.shape

(299, 28)

In [ ]:
#Missing Values
df.isnull().sum()

surgery                    0
age                        0
hospital_number            0
rectal_temp               60
pulse                     24
respiratory_rate          58
temp_of_extremities       56
peripheral_pulse          69
mucous_membrane           47
capillary_refill_time     32
pain                      55
peristalsis               44
abdominal_distention      56
nasogastric_tube         104
nasogastric_reflux       106
nasogastric_reflux_ph    246
rectal_exam_feces        102
abdomen                  118
packed_cell_volume        29
total_protein             33
abdomo_appearance        165
abdomo_protein           198
outcome                    0
surgical_lesion            0
lesion_1                   0
lesion_2                   0
lesion_3                   0
cp_data                    0
dtype: int64

In [ ]:
# Handle the Missing values for categorical Variables
for i in ['surgery', 'age','temp_of_extremities', 'peripheral_pulse','mucous_membrane', 'capillary_refill_time', 'pain', 'peristalsis','abdominal_distention', 'nasogastric_tube', 'nasogastric_reflux','nasogastric_reflux_ph', 'rectal_exam_feces', 'abdomen','abdomo_appearance','outcome', 'surgical_lesion','cp_data']: 
  df[i].fillna(value=df[i].mode()[0],inplace=True)

In [ ]:
df.isnull().sum()

surgery                    0
age                        0
hospital_number            0
rectal_temp               60
pulse                     24
respiratory_rate          58
temp_of_extremities        0
peripheral_pulse           0
mucous_membrane            0
capillary_refill_time      0
pain                       0
peristalsis                0
abdominal_distention       0
nasogastric_tube           0
nasogastric_reflux         0
nasogastric_reflux_ph      0
rectal_exam_feces          0
abdomen                    0
packed_cell_volume        29
total_protein             33
abdomo_appearance          0
abdomo_protein           198
outcome                    0
surgical_lesion            0
lesion_1                   0
lesion_2                   0
lesion_3                   0
cp_data                    0
dtype: int64

In [ ]:
# Handle the Missing Values for Numerical Variables
for i in ['rectal_temp','pulse','respiratory_rate','packed_cell_volume','total_protein','abdomo_protein']:
  df[i].fillna(value=df[i].mean(),inplace=True)

In [ ]:
df.isnull().sum()

surgery                  0
age                      0
hospital_number          0
rectal_temp              0
pulse                    0
respiratory_rate         0
temp_of_extremities      0
peripheral_pulse         0
mucous_membrane          0
capillary_refill_time    0
pain                     0
peristalsis              0
abdominal_distention     0
nasogastric_tube         0
nasogastric_reflux       0
nasogastric_reflux_ph    0
rectal_exam_feces        0
abdomen                  0
packed_cell_volume       0
total_protein            0
abdomo_appearance        0
abdomo_protein           0
outcome                  0
surgical_lesion          0
lesion_1                 0
lesion_2                 0
lesion_3                 0
cp_data                  0
dtype: int64

In [ ]:
#Label Encoder
from sklearn.preprocessing import LabelEncoder
ln=LabelEncoder()
for i in ['surgery', 'age','temp_of_extremities', 'peripheral_pulse','mucous_membrane', 'capillary_refill_time', 'pain', 'peristalsis','abdominal_distention', 'nasogastric_tube', 'nasogastric_reflux','nasogastric_reflux_ph', 'rectal_exam_feces', 'abdomen','abdomo_appearance','outcome', 'surgical_lesion','cp_data']: 
  df[i]=ln.fit_transform(df[i])

In [ ]:
df.head()

surgery  age  hospital_number  ...  lesion_2  lesion_3  cp_data
0        0    0           530101  ...         0         0        0
1        1    0           534817  ...         0         0        0
2        0    0           530334  ...         0         0        1
3        1    1          5290409  ...         0         0        1
4        0    0           530255  ...         0         0        0

[5 rows x 28 columns]

In [ ]:
df.shape

(299, 28)

In [ ]:
#Feature
x=df.drop(columns=['outcome'],axis=1)
#Target
y=df[['outcome']]

In [ ]:
# Split the data into train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
#Create the model
from sklearn.tree import DecisionTreeClassifier
dtc= DecisionTreeClassifier()
dtc.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
y_pred=dtc.predict(x_test)

In [ ]:
#Accuracy Metrics
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print('Decision Tree:')
print(f'Accuracy:{accuracy_score(y_pred,y_test)}')
print(f'Confusion Matrix:{confusion_matrix(y_pred,y_test)}')
print(f'Classification Report:{classification_report(y_pred,y_test)}')

Decision Tree:
Accuracy:0.6111111111111112
Confusion Matrix:[[16  0 11]
 [ 3  7  7]
 [ 9  5 32]]
Classification Report:              precision    recall  f1-score   support

           0       0.57      0.59      0.58        27
           1       0.58      0.41      0.48        17
           2       0.64      0.70      0.67        46

    accuracy                           0.61        90
   macro avg       0.60      0.57      0.58        90
weighted avg       0.61      0.61      0.61        90



In [ ]:
# RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
y_pred=rf.predict(x_test)

In [ ]:
#Accuracy Metrics
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print('Random Forest:')
print(f'Accuracy:{accuracy_score(y_pred,y_test)}')
print(f'Confusion Matrix:{confusion_matrix(y_pred,y_test)}')
print(f'Classification Report:{classification_report(y_pred,y_test)}')

Random Forest:
Accuracy:0.7444444444444445
Confusion Matrix:[[19  2  4]
 [ 1  3  1]
 [ 8  7 45]]
Classification Report:              precision    recall  f1-score   support

           0       0.68      0.76      0.72        25
           1       0.25      0.60      0.35         5
           2       0.90      0.75      0.82        60

    accuracy                           0.74        90
   macro avg       0.61      0.70      0.63        90
weighted avg       0.80      0.74      0.76        90

